### ISSUE TITLE
Initial suggestions for plugin release

### ISSUE THREAD

**Issue by misraved** [tomba-io/steampipe-plugin-tomba#1]
Thanks @benemohamed for this new plugin. Great work 🎉 !!

The basic structure looks good so far. While using the plugin, we did come up with a few suggestions based on our best practices:

- `config/tomba.spc`
    - Could you please update the tomba.spc file to follow the format of the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/config/namecheap.spc)
    - Both the `key` and `secret` parameters should be commented out and the values should be in the format of the actual values (however incorrect)
    - For instance:
    ```
    connection "tomba" {
        # plugin = "tomba-io/tomba"
        # `key`: Tomba API Key.(Required)
        # `secret`: Tomba API secret. (Required)
        # Sign up for a free API and SECRET Keys at https://app.tomba.io/auth/register
        # This can also be set via the `TOMBA_KEY` and `TOMBA_SECRET` environment variables.
        # key = "ta_d40f89cc3b7f59a0638e1234a22fdfa9d3b86"
        # secret = "ts_121f9gf4-6f90-4856-9017-b12b5079adc9"
    }
    ```
- `docs/tables/*`
    - The example queries in the doc look a bit light. Could you please add 2-3 more example queries per table.
    - One suggestion would be to reflect the column names instead of using `*` for all the example queries
    - Examples around JSON coulumns are also a good way to indicate the usage of the tables
    - We generally don't keep the output of the queries in the table docs.
    - Instead of adding a `NOTES` section which mention the key columns, I think you could add them in a separate line below the table description. For instance - 
    ```
    # Table: tomba_author

    Get detailed information of email address from a blog post url.
    
    The `tomba_author` table requires the `url` field to be specified in all queries, defining the URL to lookup.
    ```
    - Also please update the format of the example queries using https://www.freeformatter.com/sql-formatter.html#before-output (2 indent spaces)

- `docs/index.md`
    - The overall structure of the index.md file looks correct to me
    - The install section should be updated to use the `steampipe plugin install tomba-io/tomba` command instead of `steampipe plugin install tomba``
    - Minor formatting changes need to be made per https://github.com/turbot/steampipe-plugin-namecheap/blob/main/docs/index.md
    - Also please make sure that the [Configuration](https://github.com/tomba-io/steampipe-plugin-tomba/blob/master/docs/index.md#configuration) section is in sync with the changes suggested for the `config/tomba.spc` file.
    - Please update the format of the example query using https://www.freeformatter.com/sql-formatter.html#before-output (2 indent spaces)

- `README`
    - The overall format of the README file looks correct
    The install section should be updated to use the `steampipe plugin install tomba-io/tomba`
    - Could you please make minor updates to follow the format mentioned in https://github.com/turbot/steampipe-plugin-namecheap/blob/main/README.md
    - Also please update the format of the example query using https://www.freeformatter.com/sql-formatter.html#before-output (2 indent spaces)

- `go.mod`
    - Please update the Steampipe plugin SDK to use the latest `5.4.1` version

- `Makefile`
    - Please update the install command as follows - 
        `go build -o ~/.steampipe/plugins/hub.steampipe.io/plugins/tomba-io/tomba@latest/steampipe-plugin-tomba.plugin *.go`

- `tomba/*`
    - In the `plugin.go` file could you please sort the table list - https://github.com/tomba-io/steampipe-plugin-tomba/blob/master/tomba/plugin.go#L19-L24
    - Overall could you please update the `KeyColumns` section of the tables to follow a uniform format? Maybe using `go fmt` command will fix the overall formatting of the go files
    - Certain columns for instance `url` and `company` in the `tomba_author` table do not have periods. Could you please make sure that all the column descriptions have periods at the end?
    - Could we remove the commented column in https://github.com/tomba-io/steampipe-plugin-tomba/blob/master/tomba/table_tomba_verifier.go#L43-L47

- A couple of follow-up questions:
    - How are we handling the resource not found errors?
    - Do the APIs support pagination? I did not find any reference to it, but I want to make sure that we have checked that box before releasing it.
    - While working with the APIs did you encounter rate limit errors? 
    - Please refer https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion for more information
    
 Please let us know if you have questions, happy to help 👍.

**Comment by benemohamed** [comment]
Thanks @misraved for help and suggestions

- handling error with error Error: response
- The APIs do not offer support for pagination.
- i didn't encounter any rate limit errors

**Comment by misraved** [comment]
Thanks @benemohamed for the response and for quickly making the updates 👍.

Will you be adding more example queries to the table docs?

**Comment by misraved** [comment]
@benemohamed the example query updates look good, however, we don't usually keep the query outputs in the doc files. Is there a specific reason why you want to keep the query outputs?

**Comment by benemohamed** [comment]
@misraved Sorry for this; I will delete the outputs in the doc files

**Comment by misraved** [comment]
@benemohamed thanks for making all the changes, I took a final look at the plugin and I believe there a review comments that need to be addressed:

- The following query results can be removed:
  - https://github.com/tomba-io/steampipe-plugin-tomba/blob/master/docs/tables/tomba_author.md#info-about-an-author-finder, quick question, do we need the `query any blog post URL` query description? I feel the title is good enough for the query
  - https://github.com/tomba-io/steampipe-plugin-tomba/blob/master/docs/tables/tomba_count.md#info-about-an-email-count
  - https://github.com/tomba-io/steampipe-plugin-tomba/blob/master/docs/tables/tomba_enrich.md#info-about-an-enrichment
  - https://github.com/tomba-io/steampipe-plugin-tomba/blob/master/docs/tables/tomba_linkedin.md#info-about-an-linkedin-finder
- On a side note, I believe the queries need some more formatting. Could you please update the formatting of queries using https://www.freeformatter.com/sql-formatter.html#before-output (2 spaces per indent level)
- The descriptions for the columns in https://github.com/tomba-io/steampipe-plugin-tomba/blob/master/tomba/table_tomba_count.go#L48-L57 are missing the `.` period.
- The organization parameter in `docs/index.md` file should be updated to use `organization: tomba-io` instead of `organization: Turbot`

The above-suggested changes are very minor, overall the plugin looks great 😃.

Can't wait to push it to the hub 👍.

**Comment by misraved** [comment]
Thanks @benemohamed for making the changes so proactively 👍.

Since all the review suggestions have now been addressed, could you please update the CHANGELOG file with the names of the tables that have been added? Please refer https://github.com/turbot/steampipe-plugin-namecheap/blob/main/CHANGELOG.md#v001-2023-02-25 for more information on how to structure the initial plugin release.

Once that is completed, please push an initial release tag - `v0.0.1`, following which we will trigger our build process to publish the plugin to the hub 👍.

**Comment by benemohamed** [comment]
Done 👍🏼

Thanks @misraved
